variable "instance_type" {}
variable "env" {}
variable "zone_id" {}
variable "vault_token" {}
variable "vpc_ip_block" {}
variable "subnet_ip_block" {}
variable "default_vpc_id" {}
variable "default_vpc_ip_block" {}
variable "default_rtb_id" {}