format_version: 10
pipelines:
  expense-tf-destroy:
    group: Terraform
    label_template: ${COUNT}
    lock_behavior: none
    display_order: -1
    materials:
      git-1ce9e45:
        git: https://github.com/devops-iterration1/expense-terraform.git
        shallow_clone: false
        auto_update: true
        branch: main
    stages:
      - DEV:
          fetch_materials: true
          environment_variables:
            env: dev
          keep_artifacts: false
          clean_workspace: false
          approval:
            type: manual
          jobs:
            terraform-apply:
              tasks:
                - exec: {command: terraform, arguments: ["init", "-backend-config=env-dev/state.tfvars"], run_if:passed}
                - exec: {command: terraform, arguments: ["destroy", "-var-file=env-dev/main.tfvars", "-auto-approve"], run_if:passed}
