format_version: 10
pipelines:
  expense-tf-apply:
    group: Expense-app
    label_template: ${COUNT}
    lock_behavior: none
    display_order: -1
    materials:
      git-1ce9e45:
        git: https://github.com/devops-iterration1/expense-terraform.git
        shallow_clone: false
        auto_update: true
        branch: main
    secure_variables:
      TF_VAR_vault_token: AES:1ZXIK3WRT8g96RLKIxRBeQ==:+Wp1pqBK1w6BHiBz36L/Psa/AJrohEl9jXrSbk+ho3k=
    stages:
      - DEV:
          fetch_materials: true
          environment_variables:
            env: dev
          keep_artifacts: false
          clean_workspace: false
          approval:
            type: manual
          jobs:
            terraform-apply:
              tasks:
              - exec: {command: terraform, arguments: [ "init", "-backend-config=env-dev/state.tfvars" ], run_if: passed}
              - exec: {command: terraform, arguments: [ "apply", "-var-file=env-dev/main.tfvars", "-auto-approve" ], run_if: passed}
